[package]
name = "bedrock-vuln"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest = { version = "0.12", features = ["json"] }
tokio.workspace = true
dirs = "5.0"
bedrock-sbom = { path = "../bedrock-sbom" }
chrono = "0.4"
