[package]
name = "bedrock-trace"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
bedrock-fs = { path = "../bedrock-fs" }
bedrock-sbom = { path = "../bedrock-sbom" }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.28", features = ["ptrace", "process", "signal", "user", "mount", "fs"] }
goblin = "0.8"
