name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Run tests (Self-test)
        run: cargo test --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/bedrock
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  snap:
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - uses: actions/checkout@v3
      - name: Build Snap
        uses: snapcore/action-build@v1
      - name: Publish Snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
